version: "3.9"

services:
  # Backend service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - PORT=${BACKEND_PORT:-5000}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb+srv://nguyenminhdoan0303:minhdoan0303@cluster0.fjj6e.mongodb.net/Project1?retryWrites=true&w=majority
    depends_on:
      - mongo
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
      - ./server/uploads:/usr/src/app/src/uploads
    restart: unless-stopped
    networks:
      - app-network

  # Frontend service
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - VITE_API_ENDPOINT=http://backend:${BACKEND_PORT:-5000}/api
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  # Database service (local Mongo)
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
